CSCBelgium/CSCBelgium/ViewModels/AddBrandViewModel.cs
using CSCBelgium.DAO.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class AddBrandViewModel
    {
        public ICollection<tblBrands> brands { get; set; }
       
        public tblBrands newBrand { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/AddCarViewModel.cs
using CSCBelgium.DAO.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CSCBelgium.Views.Configuratiepaneel.CustomCode;

namespace CSCBelgium.ViewModels
{
    public class AddCarViewModel
    {
        public tblCars car { get; set; }
        public int selectedBrandId { get; set; }
        public IEnumerable<tblBrands> brandChoice { get; set; }
        public int selectedColorId { get; set; }
        public IEnumerable<tblColors> colorChoice { get; set; }
        public Fuel fuelChoice { get; set; }
        public Transmission transmissionChoice { get; set; }
        public IEnumerable<HttpPostedFileBase> files { get; set; }

    }
}

CSCBelgium/CSCBelgium/ViewModels/AddColorViewModel.cs
using CSCBelgium.DAO.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class AddColorViewModel
    {
        public ICollection<tblColors> colors { get; set; }
        public tblColors newColor { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/AddPostViewModel.cs
using CSCBelgium.DAO.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class AddPostViewModel
    {
        public tblPosts post { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/AddRimBrandViewModel.cs
using CSCBelgium.DAO.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class AddRimBrandViewModel
    {
        public ICollection<tblRimBrands> brands { get; set; }
        public tblRimBrands newBrand { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/AddRimViewModel.cs
using CSCBelgium.DAO.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class AddRimViewModel
    {
        public tblRims rim { get; set; }
        public IEnumerable<tblRimBrands> brandChoice { get; set; }
        public int selectedBrandId { get; set; }
        public IEnumerable<HttpPostedFileBase> files { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/AddSliderImageViewModel.cs
using CSCBelgium.DAO.Model;
using CSCBelgium.Views.Configuratiepaneel.CustomCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class AddSliderImageViewModel
    {
        public tblSlides newSlide { get; set; }
        public Uitlijning alignment { get; set; }
        
    }
}

CSCBelgium/CSCBelgium/ViewModels/CarIndexViewModel.cs
using CSCBelgium.DAO.Model;
using CSCBelgium.Views.Configuratiepaneel.CustomCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class CarIndexViewModel
    {
        public ICollection<tblCars> Cars { get; set; }
        public ICollection<tblImages> Images { get; set; }
        public int CarsInStock { get; set; }
        public JaNee JaNee { get; set;}
        public JaNee NeeJa { get; set; }
        public string parameter { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/EditCarViewModel.cs
using CSCBelgium.DAO.Model;
using CSCBelgium.Views.Configuratiepaneel.CustomCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class EditCarViewModel
    {
        public tblCars car { get; set; }
        public int selectedBrandId { get; set; }
        public IEnumerable<tblBrands> brandChoice { get; set; }
        public int selectedColorId { get; set; }
        public IEnumerable<tblColors> colorChoice { get; set; }
        public Fuel fuelChoice { get; set; }
        public Transmission transmissionChoice { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/EditPostsViewModel.cs
using CSCBelgium.DAO.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class EditPostsViewModel
    {
        public ICollection<tblPosts> Posts { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/ManageRimsViewModel.cs
using CSCBelgium.DAO.Model;
using CSCBelgium.Views.Configuratiepaneel.CustomCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSCBelgium.ViewModels
{
    public class ManageRimsViewModel
    {
        public ICollection<tblRims> rims { get; set; }
        public JaNee janee { get; set; }
        public JaNee neeja { get; set; }
        public int RimsInStock { get; set; }
        public ICollection<tblRimImages> images { get; set; }
    }
}

CSCBelgium/CSCBelgium/ViewModels/ManageSliderImagesViewModel.cs
using CSCBelgium.DAO.Model;
using CSCBelgium.Views.Configuratiepaneel.CustomCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSCBelgium.ViewModels
{
    public class ManageSliderImagesViewModel
    {
        public ICollection<tblSlides> slides { get; set; }
        public Uitlijning LinksEerst { get; set; }
        public Uitlijning MiddenEerst { get; set; }
        public Uitlijning RechtsEerst { get; set; }
        public ICollection<int> order { get; set; }
        public ICollection<List<SelectListItem>> orderlist { get; set; }
        public int selectedInt { get; set; }
    }
}

CSCBelgium/CSCBelgium/Controllers/ConfiguratiepaneelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSCBelgium.Service;
using CSCBelgium.ViewModels;
using CSCBelgium.DAO.Model;
using System.IO;
using System.Diagnostics;
using System.Web.Mvc.Ajax;
using CSCBelgium.Views.Configuratiepaneel.CustomCode;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Drawing.Imaging;

namespace CSCBelgium.Controllers
{
    public class ConfiguratiepaneelController : Controller
    {
        // GET: Configuratiepaneel
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult EditPosts()
        {
            EditPostsViewModel vm = new EditPostsViewModel();
            tblPostsService service = new tblPostsService();
            vm.Posts = service.getAllPosts();
            return View(vm);
        }
        [Authorize]
        public ActionResult AddPost()
        {
            //tblPostsService service = new tblPostsService();
            //ICollection<tblPosts> posts = service.getAllPosts();

            //for (int i = 0; i < posts.Count(); i++)
            //{
            //    tblPosts temp = posts.ElementAt(i);
            //    temp.PostImage = ResizeImage(temp.PostImage, 0.70f);
            //    service.UpdatePost(temp);
            //}
            return View();
        }

        [Authorize]
        public ActionResult EditCar(int carID)
        {
            EditCarViewModel vm = new EditCarViewModel();
            tblCarsService cservice = new tblCarsService();
            tblColorsService colservice = new tblColorsService();
            tblBrandsService bservice = new tblBrandsService();
            vm.car = cservice.getCar(carID);
            vm.selectedBrandId = vm.car.BrandID;
            vm.selectedColorId = vm.car.ColorID;
            vm.brandChoice = bservice.getBrands();
            vm.colorChoice = colservice.getColors();
            vm.fuelChoice = (Fuel)Enum.Parse(typeof(Fuel), vm.car.CarFuel, true);
            vm.transmissionChoice = (Transmission)Enum.Parse(typeof(Transmission), vm.car.Transmission, true);

            return View(vm);

        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCar(AddCarViewModel vm)
        {

            tblCarsService cservice = new tblCarsService();
            tblColorsService colservice = new tblColorsService();
            tblBrandsService bservice = new tblBrandsService();
            tblImagesService iservice = new tblImagesService();
            tblCars car = cservice.getCar(vm.car.CarID);
            car.BrandID = vm.selectedBrandId;
            car.ColorID = vm.selectedColorId;
            car.CarModel = vm.car.CarModel;
            car.CarDescription = vm.car.CarDescription;
            car.CarFuel = vm.fuelChoice.ToString();
            car.CarKilometers = vm.car.CarKilometers;
            car.CarPrice = vm.car.CarPrice;
            car.CarEquipment = vm.car.CarEquipment;
            car.CarYearOfConstruction = vm.car.CarYearOfConstruction;
            car.Sold = (byte)0;
            car.C02Emissions = vm.car.C02Emissions;
            car.PowerKW = vm.car.PowerKW;
            car.PowerPK = vm.car.PowerPK;
            car.CylinderCapacity = vm.car.CylinderCapacity;
            car.FirstRegistration = vm.car.FirstRegistration;
            car.Transmission = vm.transmissionChoice.ToString();
            car.Createdate = DateTime.Now.Date;
            cservice.editCar(car);
            List<HttpPostedFileBase> files = vm.files.ToList();
            //ICollection<tblImages> images = cservice.GetImagesByCar(car);
            //for (int i = 0; i < images.Count() ; i++)
            //{
            //    tblImages temp = images.ElementAt(i);
            //    temp.Image = ResizeImage(temp.Image, 0.70f);
            //    iservice.UpdateImage(temp);
            //}
            for (int i = 0; i < files.Count(); i++)
            {
                if (files.ElementAt(i) != null && files.ElementAt(i).ContentLength > 0)
                {
                    if (i == 0)
                    {
                        iservice.DeleteAllImagesOfCar(vm.car);
                    }
                    tblImages Image = new tblImages();
                    System.Diagnostics.Debug.WriteLine("image");
                    MemoryStream target = new MemoryStream();
                    files.ElementAt(i).InputStream.CopyTo(target);
                    byte[] image = target.ToArray();
                    Image.CarID = car.CarID;
                    Image.ImageOrder = i;
                    Image.ImagePath = "Temp";
                    iservice.AddImage(Image);
                    Image.ImagePath = @"Cars/Car" + car.CarID + @"/Image" + Image.ImageID + ".jpg";
                    iservice.UpdateImage(Image);
                    

                }
                else
                {
                    Debug.WriteLine("file null");
                    return RedirectToAction("CarIndex");

                }

            }
            return RedirectToAction("CarIndex");


        }
        [Authorize]
        public ActionResult AddCar()
        {
            AddCarViewModel vm = new AddCarViewModel();
            tblCarsService cservice = new tblCarsService();
            tblColorsService colservice = new tblColorsService();
            tblBrandsService bservice = new tblBrandsService();
            vm.brandChoice = bservice.getBrands();
            vm.colorChoice = colservice.getColors();
            return View(vm);

        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCar(AddCarViewModel vm)
        {
            tblCarsService cservice = new tblCarsService();
            tblColorsService colservice = new tblColorsService();
            tblBrandsService bservice = new tblBrandsService();
            tblCars car = new tblCars();
            car.BrandID = vm.selectedBrandId;
            car.ColorID = vm.selectedColorId;
            car.CarModel = vm.car.CarModel;
            car.CarDescription = vm.car.CarDescription;
            car.CarFuel = vm.fuelChoice.ToString();
            car.CarKilometers = vm.car.CarKilometers;
            car.CarPrice = vm.car.CarPrice;
            car.CarEquipment = vm.car.CarEquipment;
            car.CarYearOfConstruction = vm.car.CarYearOfConstruction;
            car.Sold = (byte)0;
            car.C02Emissions = vm.car.C02Emissions;
            car.PowerKW = vm.car.PowerKW;
            car.PowerPK = vm.car.PowerPK;
            car.CylinderCapacity = vm.car.CylinderCapacity;
            car.FirstRegistration = vm.car.FirstRegistration;
            car.Transmission = vm.transmissionChoice.ToString();
            car.Createdate = DateTime.Now.Date;
            cservice.addCar(car);
            List<HttpPostedFileBase> files = vm.files.ToList();
            for (int i = 0; i < files.Count(); i++)
            {
                if (files.ElementAt(i) != null && files.ElementAt(i).ContentLength > 0)
                {
                    tblImages Image = new tblImages();
                    System.Diagnostics.Debug.WriteLine("image");
                    Image.CarID = car.CarID;
                    Image.ImageOrder = i;
                    Image.ImagePath =@"Cars\Car"+car.CarID+@"\Image";
                    tblImagesService iservice = new tblImagesService();
                    iservice.AddImage(Image);
                    Image.ImagePath = @"Cars/Car" + car.CarID + @"/Image" + Image.ImageID+".jpg" ;
                    iservice.UpdateImage(Image);
                    CSCBelgiumCloudService cloudservice = new CSCBelgiumCloudService();
                    cloudservice.UploadImageAsBlob(Image, files.ElementAt(i));

                }
                else
                {
                    Debug.WriteLine("file null");

                }

            }
            return RedirectToAction("CarIndex");


        }
        [Authorize]
        public ActionResult AddColor()
        {
            tblColorsService service = new tblColorsService();
            AddColorViewModel vm = new AddColorViewModel();
            vm.colors = service.getColors();
            return View(vm);
        }
        [Authorize]
        public ActionResult ManageSliderImages()
        {
            tblSlidesService service = new tblSlidesService();
            ManageSliderImagesViewModel vm = new ManageSliderImagesViewModel();
            vm.slides = service.getSlides();
            vm.LinksEerst = Uitlijning.Links;
            vm.MiddenEerst = Uitlijning.Midden;
            vm.RechtsEerst = Uitlijning.Rechts;
            vm.order = service.getSlides().Select(a => a.SlideOrder).ToList();



            return View(vm);
        }
        [Authorize]
        public ActionResult addSliderImage()
        {

            AddSliderImageViewModel vm = new AddSliderImageViewModel();
            //tblCarsService sservice = new tblCarsService();
            //ICollection<tblCars> cars = sservice.getAllCars();
            //for (int i = 0; i < cars.Count; i++)
            //{
            //    ICollection<tblImages> images = sservice.GetImagesByCar(cars.ElementAt(i));
            //    for (int j = 0; j < images.Count; j++)
            //    {
            //        string filename = "Image" + images.ElementAt(j).ImageID + ".jpg";
            //        System.IO.Directory.CreateDirectory(AppDomain.CurrentDomain.BaseDirectory + @"Content\Filesystem");
            //        System.IO.Directory.CreateDirectory(AppDomain.CurrentDomain.BaseDirectory + @"Content\Filesystem\Cars\Car" + cars.ElementAt(i).CarID);

            //        var fs = new BinaryWriter(new FileStream(AppDomain.CurrentDomain.BaseDirectory + @"Content\Filesystem\Cars\Car" + cars.ElementAt(i).CarID + @"\" + filename, FileMode.Append, FileAccess.Write));

CSCBelgium/CSCBelgium/Views/Configuratiepaneel/AddBrand.cshtml
@model CSCBelgium.ViewModels.AddBrandViewModel
@{
    ViewBag.Title = "AddBrand";
    Layout = "~/Views/Shared/_LayoutConfiguratiepaneel.cshtml";
}

@using CSCBelgium.Views.Configuratiepaneel.CustomCode
<nav style="height:90px;">

    <div class="nav-wrapper">
        <a style="float:right;" href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>

    </div>
</nav>
<div class="main">
    <h4>Een merk toevoegen</h4>

    <div class="row">
        <div class="col-md-12">
            <section id="loginForm">
                <div class="contactform">
                    @using (Html.BeginForm("AddBrand", "Configuratiepaneel", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="row">
                            <table id="tabel" class="table">
                                <thead>
                                    <tr>
                                        <th>merk naam</th>
                                        <th></th>
                                    </tr>
                                </thead>

                                @for (int i = 0; i < Model.brands.Count(); i++)
                                {
                                    <tr id=@i>
                                        <td>@Model.brands.ElementAt(i).BrandName</td>
                                        <td>@Ajax.RawActionLink(string.Format("<i class='material-icons tooltipped' data-position='bottom' data-delay='1' data-tooltip='Merk verwijderen'>close</i>"), "VerwijderMerk", null, new { id = Model.brands.ElementAt(i).BrandID }, new AjaxOptions { HttpMethod = "DELETE", Confirm = "Ben je zeker dat je dit merk wilt verwijderen?", OnComplete = string.Format("DeleteRijInTabel({0})", i) }, new { @class = "class" })</td>
                                    </tr>

                                }
                            </table>
                        </div>
                        <div class="row">
                            <div class="input-field col s12 form">
                                @Html.LabelFor(m => m.newBrand.BrandName, new { @for = "txtNewBrandName" })
                                @Html.TextBoxFor(m => m.newBrand.BrandName, new { @class = "validate", id = "txtNewBrandName" })


                            </div>
                        </div>


                        <div class="row">
                            <div class="input-field col s12 form">
                                <input type="submit" value="Aanmaken" class="btn btn-default" />


                            </div>
                        </div>



                    }
                </div>
            </section>
        </div>

    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
                function DeleteRijInTabel(id) {
                    console.log(id);
                    console.log("completed");
                    $("#" + id).remove();
                }

    </script>
}

CSCBelgium/CSCBelgium/Views/Configuratiepaneel/AddCar.cshtml
@model CSCBelgium.ViewModels.AddCarViewModel
@{
    ViewBag.Title = "AddCar";
    Layout = "~/Views/Shared/_LayoutConfiguratiepaneel.cshtml";
}

<nav style="height:90px;">
    <div class="nav-wrapper">
        <a style="float:right;" href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left"></ul>

    </div>
</nav>
<div class="main">
    <h4>Een auto toevoegen</h4>

    <div class="row">
        <div class="col-md-12">
            <section id="loginForm">
                <div class="contactform">
                    @using (Html.BeginForm("AddCar", "Configuratiepaneel", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="input-field col s12">
                                    @Html.DropDownListFor(model => model.selectedBrandId, new SelectList(Model.brandChoice, "BrandID", "BrandName"), "Kies een merk... ")
                                    <label>Merk</label>
                                </div>
                                </div>
                            <div class="row">
                                <div class="input-field col s12 form">
                                    @Html.LabelFor(m => m.car.CarModel, new { @for = "txtCarModel" })
                                    @Html.TextBoxFor(m => m.car.CarModel, new { @class = "validate", id = "txtCarModel" })


                                </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12 form">
                                        @Html.LabelFor(m => m.car.CarPrice, new { @for = "txtCarPrice" })
                                        @Html.TextBoxFor(m => m.car.CarPrice, new { @class = "validate", id = "txtCarPrice" })


                                    </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.CarDescription, new { @for = "txtCarDescription" })
                                            @Html.TextBoxFor(m => m.car.CarDescription, new { @class = "validate", id = "txtCarDescription" })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.CarEquipment, new { @for = "txtCarSpecification" })
                                            @Html.TextAreaFor(m => m.car.CarEquipment, new { @class = "validate materialize-textarea", id = "txtCarSpecification" })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.DropDownListFor(model => model.selectedColorId, new SelectList(Model.colorChoice, "ColorID", "ColorName"), "Kies een kleur... ")
                                            <label>Kleur</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.EnumDropDownListFor(model => model.fuelChoice, "Kies een brandstof... ")
                                            <label>Brandstof</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.EnumDropDownListFor(model => model.transmissionChoice, "Kies een transmissie... ")
                                            <label>Transmissie</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.CarYearOfConstruction, new { @for = "txtCarYearOfConstruction" })
                                            @Html.TextBoxFor(m => m.car.CarYearOfConstruction, new { @class = "validate", id = "txtCarYearOfConstruction" })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.C02Emissions, new { @for = "txtC02Emissions" })
                                            @Html.TextBoxFor(m => m.car.C02Emissions, new { @class = "validate", id = "txtC02Emissions" })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.PowerPK, new { @for = "txtPowerPK" })
                                            @Html.TextBoxFor(m => m.car.PowerPK, new { @class = "validate", id = "txtPowerPK" })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.PowerKW, new { @for = "txtPowerKW" })
                                            @Html.TextBoxFor(m => m.car.PowerKW, new { @class = "validate", id = "txtPowerKW" })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.CarKilometers, new { @for = "txtCarKilometers" })
                                            @Html.TextBoxFor(m => m.car.CarKilometers, new { @class = "validate", id = "txtCarKilometers" })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.FirstRegistration, new { @for = "txtFirstRegistration" })
                                            @Html.TextBoxFor(m => m.car.FirstRegistration, new { @class = "datepicker", id = "txtFirstRegistration", })


                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            @Html.LabelFor(m => m.car.CylinderCapacity, new { @for = "txtCylinderCapacity" })
                                            @Html.TextBoxFor(m => m.car.CylinderCapacity, new { @class = "validate", id = "txtCylinderCapacity" })


                                        </div>
                                    </div>
                                    @Html.HiddenFor(m => m.brandChoice);
                                    @Html.HiddenFor(m => m.colorChoice);
                                    @Html.HiddenFor(m => m.fuelChoice);
                                    @Html.HiddenFor(m => m.transmissionChoice);

                                    <div class="row">

                                        <div class="input-field col s12 form">
                                            <div class="field">
                                                <div class="file-field input-field">
                                                    <div class="btn">
                                                        <span>Afbeeldingen</span>
                                                        <input  multiple type="file" name="files" id="files" accept="image/*">
                                                    </div>
                                                    <div class="file-path-wrapper">
                                                        <input class="file-path validate" type="text">
                                                    </div>
                                                </div>

                                            </div>


                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 form">
                                            <input type="submit" value="Aanmaken" class="btn btn-default" />


                                        </div>
                                    </div>
                                  



                    }
                                </div>
            </section>
        </div>

    </div>

</div>

CSCBelgium/CSCBelgium/Views/Configuratiepaneel/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutConfiguratiepaneel.cshtml";
}
<nav style="height:90px;">
    <div class="nav-wrapper">
        <a style="float:right;" href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
        
</div>
</nav>
<div class="main">

    <table>
        <tr>
            <td>
                <iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSKili6hpuWHROaZqh2GnlpeLCeTkYrKsQpQF5y1uFIut8P3JAN1tZ-DZe83RBmtXBiLYurUB55DyAV/pubchart?oid=2009062778&amp;format=interactive"></iframe>
            </td>
            <td>
                <iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSKili6hpuWHROaZqh2GnlpeLCeTkYrKsQpQF5y1uFIut8P3JAN1tZ-DZe83RBmtXBiLYurUB55DyAV/pubchart?oid=948559169&amp;format=interactive"></iframe>
            </td>
        </tr>
        <tr>
            <td><iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSKili6hpuWHROaZqh2GnlpeLCeTkYrKsQpQF5y1uFIut8P3JAN1tZ-DZe83RBmtXBiLYurUB55DyAV/pubchart?oid=550326728&amp;format=interactive"></iframe></td>
            <td><iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSKili6hpuWHROaZqh2GnlpeLCeTkYrKsQpQF5y1uFIut8P3JAN1tZ-DZe83RBmtXBiLYurUB55DyAV/pubchart?oid=606689560&amp;format=interactive"></iframe></td>
        </tr>
        
    </table>
    </div>